version: '3'
services:
    db:
        image: mongo:6.0.1
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: srividya
            MONGO_INITDB_ROOT_PASSWORD: srividya
        volumes:
            - ./data:/home
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
